In [1]:
import pandas as pd
from datasets import get_ed_basica, treatment_ed_basica, get_unique_municipios
from utils import start_notebook, calculate_percentage_of_group, apply_func_perc, calculate_sum_of_group, apply_func_sum

import numpy as np
import numbers

In [2]:
start_notebook()

In [3]:
ed_basica = get_ed_basica()
ed_basica = treatment_ed_basica(ed_basica)

/home/wagner/Documents/tcc-puc_minas/datasets.py:6: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [5]:
final_df = get_unique_municipios(ed_basica)
final_df = apply_func_perc( final_df, ed_basica, calculate_percentage_of_group, "CO_MUNICIPIO", "TP_DEPENDENCIA", "privado", "PERC_TP_DEPENDENCIA")
final_df = apply_func_perc( final_df, ed_basica, calculate_percentage_of_group, "CO_MUNICIPIO", "TP_LOCALIZACAO", "urbana", "PERC_TP_LOCALIZACAO")
final_df = apply_func_perc( final_df, ed_basica, calculate_percentage_of_group, "CO_MUNICIPIO", "IN_AGUA_POTAVEL", 1, "PERC_IN_AGUA_POTAVEL")
final_df = apply_func_perc( final_df, ed_basica, calculate_percentage_of_group, "CO_MUNICIPIO", "IN_ENERGIA_INEXISTENTE", 1, "PERC_IN_ENERGIA_INEXISTENTE")
final_df = apply_func_perc( final_df, ed_basica, calculate_percentage_of_group, "CO_MUNICIPIO", "IN_ESGOTO_REDE_PUBLICA", 1, "PERC_IN_ESGOTO_REDE_PUBLICA")
final_df = apply_func_perc( final_df, ed_basica, calculate_percentage_of_group, "CO_MUNICIPIO", "IN_BIBLIOTECA_SALA_LEITURA", 1, "PERC_IN_BIBLIOTECA_SALA_LEITURA")
final_df = apply_func_perc( final_df, ed_basica, calculate_percentage_of_group, "CO_MUNICIPIO", "IN_QUADRA_ESPORTES", 1, "PERC_IN_QUADRA_ESPORTES")
final_df = apply_func_perc( final_df, ed_basica, calculate_percentage_of_group, "CO_MUNICIPIO", "IN_SALA_ESTUDIO_DANCA", 1, "PERC_IN_SALA_ESTUDIO_DANCA")
final_df = apply_func_perc( final_df, ed_basica, calculate_percentage_of_group, "CO_MUNICIPIO", "IN_INTERNET", 1, "PERC_IN_INTERNET")
final_df = apply_func_perc( final_df, ed_basica, calculate_percentage_of_group, "CO_MUNICIPIO", "TP_ATIVIDADE_COMPLEMENTAR", "sim", "PERC_TP_ATIVIDADE_COMPLEMENTAR")
final_df = apply_func_sum(final_df, ed_basica, calculate_sum_of_group, "CO_MUNICIPIO", "QT_SALAS_UTILIZADAS", "SUM_QT_SALAS_UTILIZADAS")
final_df = apply_func_sum(final_df, ed_basica, calculate_sum_of_group, "CO_MUNICIPIO", "QT_DESKTOP_ALUNO", "SUM_QT_DESKTOP_ALUNO")
final_df = apply_func_sum(final_df, ed_basica, calculate_sum_of_group, "CO_MUNICIPIO", "QT_COMP_PORTATIL_ALUNO", "SUM_QT_COMP_PORTATIL_ALUNO")

In [8]:
nan_values = {
    "PERC_TP_DEPENDENCIA" : 0,
    "PERC_TP_LOCALIZACAO" : 0,
    "PERC_IN_AGUA_POTAVEL" : 100,
    "PERC_IN_ENERGIA_INEXISTENTE" : 0,
    "PERC_IN_ESGOTO_REDE_PUBLICA" : "mean",
    "PERC_IN_BIBLIOTECA_SALA_LEITURA" : 0,
    "PERC_IN_QUADRA_ESPORTES" : "mean",
    "PERC_IN_SALA_ESTUDIO_DANCA" : 0,
    "PERC_IN_INTERNET" : "mean",
    "PERC_TP_ATIVIDADE_COMPLEMENTAR" : 0,
    "SUM_QT_SALAS_UTILIZADAS" : "mean",
    "SUM_QT_DESKTOP_ALUNO" : "mean",
    "SUM_QT_COMP_PORTATIL_ALUNO" : "mean",

}

In [9]:
df = final_df
for key, value in nan_values.items():
    if isinstance(value, numbers.Number):
        df[key] = df[key].fillna(value)
    if value == "mean":
        df[key] = df[key].fillna(df[key].mean())

In [10]:
final_df.to_parquet("datasets/tratados/ed_basica_enriquecida.parquet", )

In [11]:
teste = pd.read_parquet("datasets/tratados/ed_basica_enriquecida.parquet",)

In [12]:
teste

,CO_MUNICIPIO,PERC_TP_DEPENDENCIA,PERC_TP_LOCALIZACAO,PERC_IN_AGUA_POTAVEL,PERC_IN_ENERGIA_INEXISTENTE,PERC_IN_ESGOTO_REDE_PUBLICA,PERC_IN_BIBLIOTECA_SALA_LEITURA,PERC_IN_QUADRA_ESPORTES,PERC_IN_SALA_ESTUDIO_DANCA,PERC_IN_INTERNET,PERC_TP_ATIVIDADE_COMPLEMENTAR,SUM_QT_SALAS_UTILIZADAS,SUM_QT_DESKTOP_ALUNO,SUM_QT_COMP_PORTATIL_ALUNO
0,1100015,3.448,51.724,100.000,10.345,55.098,37.931,48.276,3.448,65.517,3.448,185.000,85.000,32.000
1,1100023,22.917,83.333,97.917,0.000,4.167,75.000,68.750,0.000,100.000,2.083,612.000,585.000,106.000
2,1100031,11.111,77.778,88.889,0.000,55.098,44.444,66.667,0.000,100.000,0.000,74.000,62.000,15.000
3,1100049,16.667,64.815,100.000,1.852,53.704,57.407,46.296,3.704,98.148,3.704,541.000,460.000,60.000
4,1100056,20.000,93.333,93.333,0.000,86.667,46.667,53.333,0.000,100.000,13.333,129.000,130.000,16.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,5222005,16.667,83.333,100.000,0.000,16.667,100.000,66.667,0.000,100.000,0.000,97.000,59.000,12.000
5566,5222054,0.000,100.000,100.000,0.000,55.098,40.000,40.000,0.000,100.000,0.000,44.000,60.000,0.000
5567,5222203,0.000,71.429,100.000,0.000,55.098,42.857,57.143,0.000,100.000,0.000,43.000,34.000,4.000
5568,5222302,0.000,42.857,100.000,0.000,14.286,85.714,28.571,0.000,100.000,0.000,38.000,11.000,12.000
5569,5300108,44.690,93.464,99.673,0.000,90.768,82.190,62.337,7.190,98.693,9.967,18203.000,10562.000,2078.000